### ISSUE TITLE
Free/Paid

### ISSUE THREAD

**Issue by navalevivek** [oneall/social-login-magento#5]
Hi,

I have download downloaded this  extension in  Magento.

Is  this free for lifetime, so that  I  can  relax after downloading.

Also there is  one point you  mentioned from below link that " Please note that many social networks require that the webmasters register their website before being able to use their services. "

http://docs.oneall.com/plugins/guide/social-login-magento/

So  please  reply  your  answers on my queries.
Thanks

Any  help would  be greatly appreciated.

**Comment by SchlesserClaude** [comment]
Hello,

if the free plan suits your needs then you can use it without limitation in time.

Facebook (and many other social networks) require each webmaster to create an app before being able to use their services (for login per example) on his website/shop. This takes only a few minutes and you can find the corresponding setup guide in your OneAll account.

Regards,

**Comment by navalevivek** [comment]
suits your needs??? means, does  free  plan have limitation in terms of  functioanlity or flow?

**Comment by ghost** [comment]
The free plan provides social login and social link.
Now, there are additional features for a fee (http://www.oneall.com/pricing-and-plans/)

Regards.

**Comment by navalevivek** [comment]
ok  thanks, means in basic  free plan,  i can fulfil my  requirnment, right?

**Comment by bogdandin** [comment]
Yes

2016-01-13 14:45 GMT+02:00 navalevivek <notifications@github.com>:

**Comment by navalevivek** [comment]
oh,  thanks for so quick reply.

but when i inetgrated,i get  prob. in facebook  login  like 

"Given URL is not whitelisted in Client OAuth Settings: This redirect failed because the redirect URI is not whitelisted in the app’s Client OAuth Settings. Make sure Client and Web OAuth Login are on and add all your app domains as Valid OAuth Redirect URIs.";

**Comment by navalevivek** [comment]
And BTW,  how  shoulld I REMOVE  "Powered by OneAll Social Login"  words from login  page... after  installtions it  shows  on login  page...plz  suggest

**Comment by navalevivek** [comment]
can you reply on  above post?

**Comment by ghost** [comment]
Sure. For this, you need to upgrade from Freemium to a Basic plan (paid plan). 
Then, visit the the Site Customization page for your application (app.oneall.com).

**Comment by navalevivek** [comment]
oh shit..... so in  free version i cant remove the label  "Powered by OneAll Social Login"

and for Paid plan, what is the minimum amount?

**Comment by ghost** [comment]
Also, is the OAuth setting error for Facebook fixed?

**Comment by navalevivek** [comment]
no

**Comment by ghost** [comment]
:-)
Basic plan is $9 per month, or $8 if paid annually (http://www.oneall.com/pricing-and-plans/).
You can also reach plan information from your app (app.oneall.com) pages.

**Comment by navalevivek** [comment]
thanks  for your support till yet...nice talking you

**Comment by ghost** [comment]
You're welcome. There is a bit of info to go through initially.
For the Facebook application configuration problem, this is to be fixed in the Facebook app settings (developers.facebook.com).
In the Settings, Basic tab, make sure your web site URL is correct (https://&lt;your domain&gt;.api.oneall.com/), then, in the Advanced tab, Client OAuth Settings section, Valid OAuth redirect URIs, enter the same URL (with trailing slash).
